[package]
name = "dota2-match-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
axum = "0.7.9"
backon = "1.3.0"
clap = { version = "4.5.23", features = ["derive"] }
clickhouse = "0.13.1"
env_logger = "0.11.5"
itertools = "0.13.0"
log = "0.4.22"
primitive-types = "0.13.1"
reqwest = { version = "0.12.9", features = ["socks"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.6"
tokio = { version = "1.42.0", features = ["net", "rt-multi-thread", "io-std", "io-util", "macros", "fs"] }
